Allow page navigation after search
pulibrary/imagecat-rails pull request #146
Opened 2023-09-15 14:06 UTC by leefaisonr

2023-09-15 14:35 UTC, hackartisan requested changes
We should add a test for the search results pagination bug fixed in this PR.

2023-09-15 14:35 UTC, hackartisan commented on spec/models/guide_card_spec.rb
> +      expect(guide_card27021.index_page).to eq 2702
2703 seems right. we can update this test or remove it.

2023-09-19 15:18 UTC, leefaisonr commented on app/controllers/guide_cards_controller.rb
> +    @guide_cards = GuideCard.order(:id).page(params[:page])
I have added this logic to our controller as a comment. Thank you!

2023-09-19 16:13 UTC, hackartisan approved these changes

2023-09-19 17:55 UTC, merged